# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Patient file CI # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#name

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: # A workflow run is made up of one or more jobs. Jobs run in parallel by default.
  dbserver: # This is the first job https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: scripts
    steps:
      - run: echo "jai kali ma"

  ptserver: # This is the 2nd job Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-6
    runs-on: node:14
    defaults:
      run:
        shell: bash
        working-directory: scripts
    steps:
      - run: echo "jai kali ma"

  ptclient: # Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-8
    runs-on: node:14
    defaults:
      run:
        shell: bash
        working-directory: scripts
    steps:
      - run: echo "jai kali ma"
